/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  TimelineView: () => TimelineView,
  VaultIndexer: () => VaultIndexer,
  default: () => VaultTimelinePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  dateField: "date",
  endDateField: "endDate",
  includeFolders: [],
  excludeFolders: [],
  filterTags: [],
  orientation: "horizontal",
  defaultZoom: "month",
  colorGroups: [
    { tag: "project", color: "#4A90E2" },
    { tag: "milestone", color: "#E2844A" },
    { tag: "journal", color: "#50E3C2" },
    { tag: "task", color: "#B8E24A" }
  ],
  showExcerpt: true,
  excerptLength: 120,
  autoRefresh: true
};
var VIEW_TYPE_TIMELINE = "vault-timeline-view";
var DATE_PATTERNS = [
  /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?)?/,
  /^\d{2}[./]\d{2}[./]\d{4}/,
  /^\d{4}[/]\d{2}[/]\d{2}/
];
function parseDate(value) {
  if (!value)
    return null;
  if (typeof value === "number")
    return value;
  const str = String(value).trim();
  for (const pattern of DATE_PATTERNS) {
    if (pattern.test(str)) {
      const ts = Date.parse(str.replace(/\./g, "-").replace(/\//g, "-"));
      if (!isNaN(ts))
        return ts;
    }
  }
  return null;
}
function extractExcerpt(content, maxLen) {
  const body = content.replace(/^---[\s\S]*?---\n/, "").trim();
  const plain = body.replace(/#+\s/g, "").replace(/\*\*|__|\*|_|~~|`{1,3}/g, "").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/!\[[^\]]*\]\([^)]+\)/g, "").replace(/\n+/g, " ").trim();
  return plain.length > maxLen ? plain.slice(0, maxLen) + "\u2026" : plain;
}
var VaultIndexer = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async indexAll() {
    const files = this.app.vault.getMarkdownFiles();
    const events = [];
    for (const file of files) {
      const event = await this.indexFile(file);
      if (event)
        events.push(event);
    }
    events.sort((a, b) => a.date - b.date);
    return events;
  }
  async indexFile(file) {
    var _a, _b, _c, _d, _e;
    const { settings } = this;
    const folder = ((_a = file.parent) == null ? void 0 : _a.path) || "";
    if (settings.includeFolders.length > 0 && !settings.includeFolders.some((f) => folder.startsWith(f))) {
      return null;
    }
    if (settings.excludeFolders.some((f) => folder.startsWith(f))) {
      return null;
    }
    const metadata = this.app.metadataCache.getFileCache(file);
    const frontmatter = (_b = metadata == null ? void 0 : metadata.frontmatter) != null ? _b : {};
    const fileTags = [
      ...(_d = (_c = metadata == null ? void 0 : metadata.tags) == null ? void 0 : _c.map((t) => t.tag.replace(/^#/, ""))) != null ? _d : [],
      ...Array.isArray(frontmatter.tags) ? frontmatter.tags : []
    ];
    if (settings.filterTags.length > 0 && !settings.filterTags.some((t) => fileTags.includes(t))) {
      return null;
    }
    let date = parseDate(frontmatter[settings.dateField]);
    if (!date) {
      date = file.stat.ctime;
    }
    const endDate = (_e = parseDate(frontmatter[settings.endDateField])) != null ? _e : void 0;
    let excerpt = "";
    if (settings.showExcerpt && file.stat.size < 512e3) {
      try {
        const content = await this.app.vault.cachedRead(file);
        excerpt = extractExcerpt(content, settings.excerptLength);
      } catch (e) {
      }
    }
    return {
      id: file.path,
      title: frontmatter.title || file.basename,
      date,
      endDate,
      tags: fileTags,
      excerpt,
      icon: frontmatter.icon,
      folder
    };
  }
};
var TimelineView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.index = [];
    this.filteredEvents = [];
    // View state
    this.zoom = "month";
    this.viewStart = new Date();
    this.activeTag = "";
    this.searchQuery = "";
    this.tooltip = null;
    this.plugin = plugin;
    this.settings = plugin.settings;
    this.zoom = this.settings.defaultZoom;
  }
  getViewType() {
    return VIEW_TYPE_TIMELINE;
  }
  getDisplayText() {
    return "Vault Timeline";
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    await this.refresh();
  }
  async onClose() {
    if (this.tooltip)
      this.tooltip.remove();
  }
  async refresh() {
    this.index = this.plugin.index;
    this.applyFilters();
    this.render();
  }
  applyFilters() {
    let events = [...this.index];
    if (this.activeTag) {
      events = events.filter((e) => e.tags.includes(this.activeTag));
    }
    if (this.searchQuery) {
      const q = this.searchQuery.toLowerCase();
      events = events.filter(
        (e) => e.title.toLowerCase().includes(q) || e.excerpt.toLowerCase().includes(q) || e.tags.some((t) => t.toLowerCase().includes(q))
      );
    }
    this.filteredEvents = events;
  }
  getZoomMs() {
    switch (this.zoom) {
      case "day":
        return 864e5;
      case "week":
        return 7 * 864e5;
      case "month":
        return 30 * 864e5;
      case "year":
        return 365 * 864e5;
      case "decade":
        return 3650 * 864e5;
    }
  }
  getTagColor(tags) {
    for (const group of this.settings.colorGroups) {
      if (tags.includes(group.tag))
        return group.color;
    }
    return "var(--vt-accent)";
  }
  getAllTags() {
    const tagSet = /* @__PURE__ */ new Set();
    for (const e of this.index) {
      for (const t of e.tags)
        tagSet.add(t);
    }
    return Array.from(tagSet).sort();
  }
  render() {
    const container = this.containerEl;
    container.empty();
    container.addClass("vt-root");
    this.renderToolbar(container);
    if (this.filteredEvents.length === 0) {
      this.renderEmpty(container);
      return;
    }
    const wrapper = container.createDiv({ cls: "vt-timeline-wrapper" });
    this.renderTimeline(wrapper);
  }
  renderEmpty(container) {
    const empty = container.createDiv({ cls: "vt-empty" });
    empty.createEl("div", { cls: "vt-empty-icon", text: "\u23F3" });
    empty.createEl("h3", { text: "No events found" });
    empty.createEl("p", {
      text: "Add dates to your notes' frontmatter or adjust filters."
    });
  }
  renderToolbar(container) {
    const toolbar = container.createDiv({ cls: "vt-toolbar" });
    toolbar.createEl("span", { cls: "vt-toolbar-title", text: "Vault Timeline" });
    const searchWrap = toolbar.createDiv({ cls: "vt-search-wrap" });
    const searchInput = searchWrap.createEl("input", {
      cls: "vt-search",
      type: "text",
      placeholder: "Search events\u2026"
    });
    searchInput.value = this.searchQuery;
    searchInput.addEventListener(
      "input",
      (0, import_obsidian.debounce)(() => {
        this.searchQuery = searchInput.value;
        this.applyFilters();
        this.render();
      }, 250)
    );
    const tags = this.getAllTags();
    if (tags.length > 0) {
      const tagSelect = toolbar.createEl("select", { cls: "vt-tag-select" });
      tagSelect.createEl("option", { value: "", text: "All tags" });
      for (const tag of tags) {
        const opt = tagSelect.createEl("option", { value: tag, text: `#${tag}` });
        if (tag === this.activeTag)
          opt.selected = true;
      }
      tagSelect.addEventListener("change", () => {
        this.activeTag = tagSelect.value;
        this.applyFilters();
        this.render();
      });
    }
    const zoomGroup = toolbar.createDiv({ cls: "vt-zoom-group" });
    for (const z of ["day", "week", "month", "year", "decade"]) {
      const btn = zoomGroup.createEl("button", {
        cls: `vt-zoom-btn ${this.zoom === z ? "active" : ""}`,
        text: z.charAt(0).toUpperCase() + z.slice(1)
      });
      btn.addEventListener("click", () => {
        this.zoom = z;
        this.render();
      });
    }
    const navGroup = toolbar.createDiv({ cls: "vt-nav-group" });
    const prevBtn = navGroup.createEl("button", { cls: "vt-nav-btn", text: "\u2039" });
    prevBtn.addEventListener("click", () => {
      this.viewStart = new Date(this.viewStart.getTime() - this.getZoomMs());
      this.render();
    });
    const todayBtn = navGroup.createEl("button", { cls: "vt-nav-btn vt-today-btn", text: "Today" });
    todayBtn.addEventListener("click", () => {
      this.viewStart = new Date();
      this.render();
    });
    const nextBtn = navGroup.createEl("button", { cls: "vt-nav-btn", text: "\u203A" });
    nextBtn.addEventListener("click", () => {
      this.viewStart = new Date(this.viewStart.getTime() + this.getZoomMs());
      this.render();
    });
    const stats = toolbar.createDiv({ cls: "vt-stats" });
    stats.createEl("span", {
      text: `${this.filteredEvents.length} events`
    });
  }
  renderTimeline(container) {
    const zoomMs = this.getZoomMs();
    const viewEndMs = this.viewStart.getTime() + zoomMs;
    const viewStartMs = this.viewStart.getTime() - zoomMs;
    const visibleEvents = this.filteredEvents.filter(
      (e) => e.date >= viewStartMs && e.date <= viewEndMs
    );
    const timeline = container.createDiv({ cls: "vt-timeline" });
    this.renderAxis(timeline, viewStartMs, viewEndMs);
    const eventsTrack = timeline.createDiv({ cls: "vt-events-track" });
    for (const event of visibleEvents) {
      this.renderEvent(eventsTrack, event, viewStartMs, viewEndMs);
    }
    this.renderMinimap(container);
    if (visibleEvents.length === 0 && this.filteredEvents.length > 0) {
      const hint = container.createDiv({ cls: "vt-no-visible" });
      hint.createEl("p", { text: "No events in this range." });
      const closest = this.findClosestEvent();
      if (closest) {
        const jumpBtn = hint.createEl("button", {
          cls: "vt-jump-btn",
          text: `Jump to nearest event: ${new Date(closest.date).toLocaleDateString()}`
        });
        jumpBtn.addEventListener("click", () => {
          this.viewStart = new Date(closest.date);
          this.render();
        });
      }
    }
  }
  renderAxis(container, startMs, endMs) {
    const axis = container.createDiv({ cls: "vt-axis" });
    const totalMs = endMs - startMs;
    const tickCount = 8;
    for (let i = 0; i <= tickCount; i++) {
      const ms = startMs + totalMs / tickCount * i;
      const date = new Date(ms);
      const pct = i / tickCount * 100;
      const tick = axis.createDiv({ cls: "vt-axis-tick" });
      tick.style.left = `${pct}%`;
      const label = tick.createEl("span", { cls: "vt-axis-label" });
      label.setText(this.formatAxisDate(date));
    }
    const nowMs = Date.now();
    if (nowMs >= startMs && nowMs <= endMs) {
      const nowPct = (nowMs - startMs) / totalMs * 100;
      const nowLine = axis.createDiv({ cls: "vt-now-line" });
      nowLine.style.left = `${nowPct}%`;
      nowLine.createEl("span", { cls: "vt-now-label", text: "Now" });
    }
  }
  formatAxisDate(date) {
    switch (this.zoom) {
      case "day":
        return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      case "week":
        return date.toLocaleDateString([], { weekday: "short", day: "numeric" });
      case "month":
        return date.toLocaleDateString([], { day: "numeric", month: "short" });
      case "year":
        return date.toLocaleDateString([], { month: "short" });
      case "decade":
        return String(date.getFullYear());
    }
  }
  renderEvent(container, event, startMs, endMs) {
    const totalMs = endMs - startMs;
    const pct = (event.date - startMs) / totalMs * 100;
    const color = this.getTagColor(event.tags);
    const row = container.createDiv({ cls: "vt-event-row" });
    const dot = row.createDiv({ cls: "vt-event-dot" });
    dot.style.left = `${pct}%`;
    dot.style.setProperty("--dot-color", color);
    if (event.icon) {
      dot.createEl("span", { cls: "vt-event-icon", text: event.icon });
    }
    if (event.endDate) {
      const endPct = Math.min(100, (event.endDate - startMs) / totalMs * 100);
      const bar = row.createDiv({ cls: "vt-event-bar" });
      bar.style.left = `${pct}%`;
      bar.style.width = `${Math.max(0.5, endPct - pct)}%`;
      bar.style.setProperty("--bar-color", color);
    }
    const label = row.createDiv({ cls: "vt-event-label" });
    label.style.left = `${pct}%`;
    label.createEl("span", { cls: "vt-event-date", text: this.formatEventDate(event.date) });
    label.createEl("span", { cls: "vt-event-title", text: event.title });
    if (event.tags.length > 0) {
      const tagsEl = label.createDiv({ cls: "vt-event-tags" });
      for (const tag of event.tags.slice(0, 3)) {
        const tagEl = tagsEl.createEl("span", { cls: "vt-tag-chip", text: `#${tag}` });
        tagEl.style.setProperty("--chip-color", this.getTagColor([tag]));
      }
    }
    const showTooltip = (e) => this.showTooltip(e, event, color);
    const hideTooltip = () => this.hideTooltip();
    dot.addEventListener("mouseenter", showTooltip);
    dot.addEventListener("mouseleave", hideTooltip);
    label.addEventListener("mouseenter", showTooltip);
    label.addEventListener("mouseleave", hideTooltip);
    dot.addEventListener("click", () => {
      void this.openNote(event.id);
    });
    label.addEventListener("click", () => {
      void this.openNote(event.id);
    });
    dot.addEventListener("contextmenu", (e) => {
      const menu = new import_obsidian.Menu();
      menu.addItem(
        (item) => item.setTitle("Open note").setIcon("file-text").onClick(() => {
          void this.openNote(event.id);
        })
      );
      menu.addItem(
        (item) => item.setTitle("Go to this date").setIcon("calendar").onClick(() => {
          this.viewStart = new Date(event.date);
          this.render();
        })
      );
      menu.showAtMouseEvent(e);
    });
  }
  formatEventDate(ms) {
    const d = new Date(ms);
    switch (this.zoom) {
      case "day":
        return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      case "week":
      case "month":
        return d.toLocaleDateString([], { day: "numeric", month: "short" });
      default:
        return d.toLocaleDateString([], { day: "numeric", month: "short", year: "numeric" });
    }
  }
  showTooltip(e, event, color) {
    var _a;
    this.hideTooltip();
    const activeDoc = (_a = window.activeDocument) != null ? _a : window.document;
    const tip = activeDoc.createElement("div");
    tip.className = "vt-tooltip";
    tip.style.setProperty("--tip-color", color);
    tip.createEl("div", { cls: "vt-tip-title", text: event.title });
    tip.createEl("div", {
      cls: "vt-tip-date",
      text: new Date(event.date).toLocaleDateString([], {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric"
      })
    });
    if (event.excerpt) {
      tip.createEl("div", { cls: "vt-tip-excerpt", text: event.excerpt });
    }
    if (event.tags.length > 0) {
      const tagsEl = tip.createDiv({ cls: "vt-tip-tags" });
      for (const tag of event.tags) {
        tagsEl.createEl("span", { cls: "vt-tip-tag", text: `#${tag}` });
      }
    }
    tip.createEl("div", { cls: "vt-tip-hint", text: "Click to open \xB7 Right-click for menu" });
    activeDoc.body.appendChild(tip);
    this.tooltip = tip;
    const rect = e.target.getBoundingClientRect();
    const tipRect = tip.getBoundingClientRect();
    let left = rect.left + rect.width / 2 - tipRect.width / 2;
    let top = rect.top - tipRect.height - 10;
    left = Math.max(8, Math.min(left, window.innerWidth - tipRect.width - 8));
    if (top < 8)
      top = rect.bottom + 10;
    tip.style.left = `${left}px`;
    tip.style.top = `${top}px`;
    tip.addClass("visible");
  }
  hideTooltip() {
    if (this.tooltip) {
      this.tooltip.remove();
      this.tooltip = null;
    }
  }
  renderMinimap(container) {
    if (this.filteredEvents.length === 0)
      return;
    const minimap = container.createDiv({ cls: "vt-minimap" });
    minimap.createEl("div", { cls: "vt-minimap-label", text: "All events" });
    const track = minimap.createDiv({ cls: "vt-minimap-track" });
    const firstEvent = this.filteredEvents[0];
    const lastEvent = this.filteredEvents[this.filteredEvents.length - 1];
    if (!firstEvent || !lastEvent)
      return;
    const allMin = firstEvent.date;
    const allMax = lastEvent.date;
    const totalMs = allMax - allMin || 1;
    for (const event of this.filteredEvents) {
      const pct = (event.date - allMin) / totalMs * 100;
      const dot = track.createDiv({ cls: "vt-mini-dot" });
      dot.style.left = `${pct}%`;
      dot.style.setProperty("--dot-color", this.getTagColor(event.tags));
      dot.title = event.title;
      dot.addEventListener("click", () => {
        this.viewStart = new Date(event.date);
        this.render();
      });
    }
    const zoomMs = this.getZoomMs();
    const vpStart = this.viewStart.getTime() - zoomMs;
    const vpEnd = this.viewStart.getTime() + zoomMs;
    const vpLeft = Math.max(0, (vpStart - allMin) / totalMs * 100);
    const vpWidth = Math.min(100, (vpEnd - vpStart) / totalMs * 100);
    const vp = track.createDiv({ cls: "vt-mini-viewport" });
    vp.style.left = `${vpLeft}%`;
    vp.style.width = `${vpWidth}%`;
  }
  findClosestEvent() {
    if (this.filteredEvents.length === 0)
      return null;
    const now = this.viewStart.getTime();
    return this.filteredEvents.reduce(
      (a, b) => Math.abs(a.date - now) < Math.abs(b.date - now) ? a : b
    );
  }
  async openNote(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian.TFile) {
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
    }
  }
};
var VaultTimelineSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    this.renderSettings();
  }
  renderSettings() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Date YAML field").setDesc("Frontmatter field to use as event date (e.g. date, created)").addText(
      (text) => text.setPlaceholder("date").setValue(this.plugin.settings.dateField).onChange(async (value) => {
        this.plugin.settings.dateField = value || "date";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("End date YAML field").setDesc("Optional: frontmatter field for event end date (for duration bars)").addText(
      (text) => text.setPlaceholder("endDate").setValue(this.plugin.settings.endDateField).onChange(async (value) => {
        this.plugin.settings.endDateField = value || "endDate";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Exclude folders").setDesc("Comma-separated folder paths to exclude (e.g. Templates,Archive)").addText(
      (text) => text.setPlaceholder("Templates, Archive").setValue(this.plugin.settings.excludeFolders.join(", ")).onChange(async (value) => {
        this.plugin.settings.excludeFolders = value.split(",").map((s) => s.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Filter tags (optional)").setDesc("Only include notes with these tags (comma-separated). Leave empty for all notes.").addText(
      (text) => text.setPlaceholder("timeline, project").setValue(this.plugin.settings.filterTags.join(", ")).onChange(async (value) => {
        this.plugin.settings.filterTags = value.split(",").map((s) => s.trim().replace(/^#/, "")).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default zoom level").addDropdown(
      (dropdown) => dropdown.addOptions({
        day: "Day",
        week: "Week",
        month: "Month",
        year: "Year",
        decade: "Decade"
      }).setValue(this.plugin.settings.defaultZoom).onChange(async (value) => {
        this.plugin.settings.defaultZoom = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show excerpts in tooltips").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showExcerpt).onChange(async (value) => {
        this.plugin.settings.showExcerpt = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-refresh on vault changes").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoRefresh).onChange(async (value) => {
        this.plugin.settings.autoRefresh = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Color groups").setDesc("Assign colors to tags. The first matching tag color is used.").setHeading();
    for (let i = 0; i < this.plugin.settings.colorGroups.length; i++) {
      const group = this.plugin.settings.colorGroups[i];
      if (!group)
        continue;
      new import_obsidian.Setting(containerEl).setName(`Group ${i + 1}`).addText(
        (text) => text.setPlaceholder("tag name").setValue(group.tag).onChange(async (value) => {
          const g = this.plugin.settings.colorGroups[i];
          if (g)
            g.tag = value;
          await this.plugin.saveSettings();
        })
      ).addColorPicker(
        (picker) => picker.setValue(group.color).onChange(async (value) => {
          const g = this.plugin.settings.colorGroups[i];
          if (g)
            g.color = value;
          await this.plugin.saveSettings();
        })
      ).addButton(
        (btn) => btn.setIcon("trash").onClick(async () => {
          this.plugin.settings.colorGroups.splice(i, 1);
          await this.plugin.saveSettings();
          this.renderSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("+ Add color group").setCta().onClick(async () => {
        this.plugin.settings.colorGroups.push({ tag: "", color: "#888888" });
        await this.plugin.saveSettings();
        this.renderSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Actions").setHeading();
    new import_obsidian.Setting(containerEl).setName("Re-index vault").setDesc("Force a full re-scan of all notes.").addButton(
      (btn) => btn.setButtonText("Re-index now").setCta().onClick(async () => {
        await this.plugin.reindex();
        new import_obsidian.Notice("Vault Timeline: re-indexed successfully.");
      })
    );
  }
};
var VaultTimelinePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.index = [];
  }
  async onload() {
    await this.loadSettings();
    this.indexer = new VaultIndexer(this.app, this.settings);
    this.registerView(VIEW_TYPE_TIMELINE, (leaf) => new TimelineView(leaf, this));
    this.addCommand({
      id: "open",
      name: "Open",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "reindex",
      name: "Re-index",
      callback: async () => {
        await this.reindex();
        new import_obsidian.Notice("Vault Timeline re-indexed.");
      }
    });
    this.addRibbonIcon("calendar-clock", "Open Vault Timeline", () => {
      void this.activateView();
    });
    this.addSettingTab(new VaultTimelineSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      void this.reindex().then(() => this.registerVaultEvents());
    });
  }
  onunload() {
  }
  registerVaultEvents() {
    const refresh = (0, import_obsidian.debounce)(async () => {
      if (!this.settings.autoRefresh)
        return;
      await this.reindex();
      this.refreshViews();
    }, 1e3);
    this.registerEvent(this.app.vault.on("create", refresh));
    this.registerEvent(this.app.vault.on("delete", refresh));
    this.registerEvent(this.app.vault.on("modify", refresh));
    this.registerEvent(this.app.metadataCache.on("changed", refresh));
  }
  async reindex() {
    this.indexer = new VaultIndexer(this.app, this.settings);
    const events = await this.indexer.indexAll();
    this.index = events;
    await this.saveIndex();
    this.refreshViews();
  }
  refreshViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_TIMELINE)) {
      const view = leaf.view;
      void view.refresh();
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TIMELINE)[0];
    if (!leaf) {
      leaf = workspace.getLeaf("split");
      await leaf.setViewState({ type: VIEW_TYPE_TIMELINE, active: true });
    }
    workspace.setActiveLeaf(leaf, { focus: true });
  }
  async loadSettings() {
    var _a, _b;
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = saved == null ? void 0 : saved.settings) != null ? _a : {});
    this.index = (_b = saved == null ? void 0 : saved.index) != null ? _b : [];
  }
  async saveSettings() {
    var _a;
    const saved = (_a = await this.loadData()) != null ? _a : {};
    await this.saveData({ ...saved, settings: this.settings });
  }
  async saveIndex() {
    var _a;
    const saved = (_a = await this.loadData()) != null ? _a : {};
    await this.saveData({ ...saved, index: this.index });
  }
};


/* nosourcemap */